---
- name: Config Web VM with Docker
  hosts: webservers
  become: true
  tasks:
  - name: docker.io
    apt:
      force_apt_get: yes
      update_cache: yes
      name: docker.io
      state: present

  - name: Install pip3
    apt:
      force_apt_get: yes
      name: python3-pip
      state: present

  - name: Install Docker python module
    pip:
      name: docker
      state: present

  - name: download and launch a docker web container
    docker_container:
      name: dvwa
      image: cyberxsecurity/dvwa
      state: started
      published_ports: 80:80

  - name: Enable docker service
    systemd:
      name: docker
      enabled: yes
---
- name: Config Elk Servers with Docker
  hosts: elk
  become: yes
  tasks:
  - name: config memory
    ansible.posix.sysctl:
      name: vm.max_map_count
      value: '262144'
  - name: install docker and pip
    apt:
      update_cache: yes
      state: present
      pkg:
      - docker.io
      - python3-pip
  - name: pip3 install docker
    pip:
      name: docker
      state: present
  - name: download sebp/elk:761
    docker_container:
      name: elk
      image: sebp/elk:761
      state: started
      restart_policy: always
      published_ports:
      - 5601:5601
      - 9200:9200
      - 5044:5044
---
- name: Install FileBeat
  hosts: webservers
  become: yes
  tasks:
  - name: download filebeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.1-amd64.deb
    args:
      creates: ~/filebeat-7.6.1-amd64.deb
  - name: install filebeat
    command: dpkg -i filebeat-7.6.1-amd64.deb
  - name: copy filebeat config
    copy:
      src: ../filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml
  - name: enable filebeat system
    command: filebeat modules enable system
  - name: setup filebeat
    command: filebeat setup
  - name: start filebeat service
    command: service filebeat start